# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1

- task: CmdLine@2
  inputs:
    script: dotnet tool update dotnet-script --global

- task: CmdLine@2
  inputs:
    script: dotnet tool update dotnet-coverage --global

- task: CmdLine@2
  inputs:
    script: dotnet tool update dotnet-sonarscanner --global

- task: CmdLine@2
  inputs:
    script: |
      iwr -useb get.scoop.sh -outfile 'install.ps1'
      .\install.ps1 -RunAsAdmin
      scoop update
      scoop bucket add extras
      scoop install nsis
      makensis -VERSION
      makensis -HDRINFO

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: CmdLine@2
  inputs:
    script: dotnet build --no-incremental --no-restore -r win-x64 -f net8.0

- task: CmdLine@2
  inputs:
    script: dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"

- task: CmdLine@2
  inputs:
    script: dotnet publish -o ./publish --self-contained -r win-x64 -f net8.0