# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pr:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  RUNTIME: 'win-x64'
  FRAMEWORK: 'net8.0'
  BRANCH: $[variables['Build.SourceBranchName']]
  APPNAME: $[split(variables['Build.Repository.Name'], '/')[1]]
  PUBLISH_PATH: '.\publish\'
  OUTPUT_PATH: '.\installer\'
  YEAR: $[format('{0:yyyy}', pipeline.startTime)]

steps:
- task: PowerShell@2
  displayName: Init Vars
  inputs:
    targetType: 'inline'
    script: |
      $VERSION = Get-Content -Path VERSION -Raw
      $VERSION = $VERSION.Trim()
      Write-Host "##vso[task.setvariable variable=VERSION;]$VERSION"

      $INSTALLER_VERSION = $VERSION.Split('-')[0]
      Write-Host "##vso[task.setvariable variable=INSTALLER_VERSION;]$INSTALLER_VERSION"

      $DESCRIPTION = Get-Content -Path DESCRIPTION -Raw
      $DESCRIPTION = $DESCRIPTION.Trim()
      Write-Host "##vso[task.setvariable variable=DESCRIPTION;]$DESCRIPTION"

      $AUTHORS = Get-Content -Path AUTHORS -Raw
      $AUTHORS = $AUTHORS.Trim()
      Write-Host "##vso[task.setvariable variable=AUTHORS;]$AUTHORS"

      $AUTHORS_KEY = $AUTHORS.Replace('.', '-')
      Write-Host "##vso[task.setvariable variable=AUTHORS_KEY;]$AUTHORS_KEY"

- task: PowerShell@2
  displayName: Make installer name if main branch
  condition: eq(variables['Build.SourceBranchName'], 'main')
  inputs:
    targetType: 'inline'
    script: Write-Host "##vso[task.setvariable variable=INSTALLER_NAME;]$(APPNAME)-$(VERSION)-$(RUNTIME).exe"

- task: PowerShell@2
  displayName: Make installer name if not main branch
  condition: not(eq(variables['Build.SourceBranchName'], 'main'))
  inputs:
    targetType: 'inline'
    script: Write-Host "##vso[task.setvariable variable=INSTALLER_NAME;]$(APPNAME)-$(BRANCH)-$(VERSION)-$(RUNTIME).exe"

- script: dotnet tool update dotnet-script --global
  displayName: Install dotnet-script

- script: dotnet tool update dotnet-coverage --global
  displayName: Install dotnet-coverage

- script: dotnet tool update dotnet-sonarscanner --global
  displayName: Install dotnet-sonarscanner

- script: dotnet restore --nologo --verbosity normal --runtime $(RUNTIME)
  displayName: Restore
- task: SonarCloudPrepare@2
  inputs:
    SonarCloud: 'SonarCloud'
    organization: '$(AUTHORS_KEY)'
    scannerMode: 'MSBuild'
    projectKey: '$(AUTHORS_KEY)_$(APPNAME)'
    projectName: '$(APPNAME)'
    projectVersion: '$(VERSION)'

- script: dotnet build --nologo --verbosity normal --no-restore --no-incremental --configuration $(buildConfiguration) --runtime $(RUNTIME) --framework $(FRAMEWORK)
  displayName: Build

- script: dotnet-coverage collect "dotnet test --nologo --verbosity normal --no-build" -f xml -o "coverage.xml"
  displayName: Test

- task: SonarCloudAnalyze@2
  inputs:
    jdkversion: 'JAVA_HOME_21_X64'

- script: dotnet publish $(APPNAME)/$(APPNAME).csproj --nologo --verbosity normal --no-build --self-contained --configuration $(buildConfiguration) --runtime $(RUNTIME) --framework $(FRAMEWORK) --output $(PUBLISH_PATH)
  displayName: Publish

- script: mkdir -p $(OUTPUT_PATH)
  displayName: Create installer directory

- script: >
    makensis
    /NOCD
    /v4
    /DNAME=$(APPNAME)
    /DINSTALLER_NAME=$(INSTALLER_NAME)
    /DAUTHORS="$(AUTHORS)"
    /DVERSION=$(INSTALLER_VERSION).0
    /DDESCRIPTION="$(DESCRIPTION)"
    /DLICENSE=LICENSE
    /DCOPYRIGHT="$(AUTHORS) © $(YEAR)"
    /DYEAR=$(YEAR)
    /DMAIN_APP_EXE=$(AUTHORS).$(APPNAME).exe
    /DWEB_SITE=$(Build.Repository.Uri)
    /DPUBLISH_PATH=$(PUBLISH_PATH)
    /DOUTPUT_PATH=$(OUTPUT_PATH)
    setup.nsi
  displayName: Create Installer
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(OUTPUT_PATH)\$(INSTALLER_NAME)'
    ArtifactName: '$(INSTALLER_NAME)'
    publishLocation: 'Container'

- task: GitHubReleasePublish@1
  inputs:
    githubEndpoint: 'GitHub - matt-edmondson'
    manuallySetRepository: true
    githubOwner: '$(AUTHORS_KEY)'
    githubRepositoryName: '$(APPNAME)'
    githubTag: 'v$(VERSION)'
    githubReleaseTitle: 'v$(VERSION)'
    githubReleaseDraft: false
    githubReleasePrerelease: false
    githubIgnoreAssets: false
    githubReleaseAsset: '$(OUTPUT_PATH)\$(INSTALLER_NAME)'
    githubReuseRelease: false
    githubReuseDraftOnly: false
    githubSkipDuplicatedAssets: true
    githubEditRelease: true
    githubDeleteEmptyTag: false
    githubTargetCommitsh: '$(Build.SourceVersion)'

- task: SonarCloudPublish@2
  continueOnError: true
  inputs:
    pollingTimeoutSec: '300'