// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.BuildMonitor.UITests.Gallery;

using System.Text;

/// <summary>Writes the gallery's <c>README.md</c>, which captions each picture.</summary>
internal static class GalleryIndex
{
	/// <summary>Renders the index for the given entries, in catalog order.</summary>
	internal static string Render(IReadOnlyList<GalleryEntry> entries)
	{
		StringBuilder text = new();
		text.Append("# App gallery\n\n");
		text.Append("<!-- Generated by tests/BuildMonitor.UITests/Gallery. Edit GalleryCatalog.cs, not this file. -->\n\n");
		text.Append("BuildMonitor as it draws today, staged and photographed headlessly by the UI test harness. ");
		text.Append("The owners, repositories and runs are invented and the clock is stopped, so nothing here comes from a real CI service. ");
		text.Append("The pictures are regenerated on every successful build of `main`, so they show the current interface.\n\n");

		foreach (GalleryEntry entry in entries)
		{
			text.Append("## ").Append(entry.Name).Append("\n\n");
			text.Append(entry.Description).Append("\n\n");
			text.Append("![").Append(entry.Name).Append("](").Append(entry.Slug).Append(".png)\n\n");
		}

		return text.ToString();
	}
}
