name: Build and Analyze

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    
permissions:
  packages: write
  contents: write
  
jobs:
  build-dotnet-library:
    uses: ktsu-io/workflows/.github/workflows/build-dotnet-application.yml@main
    secrets: inherit
